ATR_PERIOD: int = 20
ATR_MULTIPLIER: float = 1.5
TRAILING_STOP_PCT: float = 0.11  # Changed from previous trial of 0.08 or higher values which were counterproductive 
TRAILING_ARM_PCT: float = 0.10
TIME_EXIT_DAYS: int = 35
KELLY_FRACTION: float = 0.5
MIN_POSITION_PCT: float = 0.01
MAX_POSITION_PCT: float = 0.05
MIN_SIGNAL_CONFIDENCE: float = 0.70